export const VALIDATION_PATTERNS = {
	WORD_CHARS: /^[a-zA-Z0-9\s\-'.,/&()]+$/,
};

export const VALIDATION_LIMITS = {
	WORD_MIN_LENGTH: 1,
	WORD_MAX_LENGTH: 20,
	SYNONYM_MIN_LENGTH: 1,
	SYNONYM_MAX_LENGTH: 20,
	SYNONYMS_MIN_COUNT: 1,
	SYNONYMS_MAX_COUNT: 20,
};
